name: Playwright Tests
on:
    push:
        branches: [ main ]
jobs:
    playwrights:
        runs-on: ubuntu-latest
        steps:
            - name: Checout repository
              uses: actions/checkout@v2
            - name: Run tests
              run: |
                npm install
                npx playwright install chromium
                npm run test:ci
