name: Playwright Tests
on:
    push:
        branches: [ main ]
        
    pull_request:
        branches: [ main ]

    workflow_dispatch:
      inputs:
        grep:
          description: 'tests to grep '
          required: false
          default: ''
        run:
          required: false
        testomatio:
          required: false
jobs:
    playwrights:
        runs-on: ubuntu-latest
        steps:
            - name: Checout repository
              uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 20.11.1
            - name: Run tests
              run: |
                npm install
                npx playwright install chromium
                npm run test -- --grep "${{ github.event.inputs.grep }}"


