name: Playwright Tests
on:
    push:
        branches: [ main ]
jobs:
    playwrights:
        runs-on: ubuntu-latest
        steps:
            - name: Checout repository
              uses: actions/checkout@v2
            - name: Say hello
              run: echo Hello
