name: Playwright Tests
on:
    push:
        branches: [ main ]
jobs:
    playwrights:
        runs-on: ubuntu-latest
        steps:
            - name: Checout repository
              uses: actions/checkout@v2
            - name: Run tests
              run: |
                echo "Install dependencies from lockfile"
                npm ci
                echo "Run playwright tests"
                npm run test:ci
